[package]
name = "hello-world"
version = "0.1.0"
authors = ["James Forcier <csssuf@csssuf.net>"]
edition = "2018"

[dependencies]
rlibc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
